### PR TITLE
better exception predicate building, closes #239

### LINKED ISSUE #239: [resilience4j-ratpack] should provide an externally configurable recordFailurePredicateClass
This should be a fqdn string that can be instantiated as a `Predicate<Throwable>`. It will need to require a no-args constructor is available.

The predicate capability in `CircuitBreakerTransformer` will be removed, and the configured predicate will be honored.

### PR DESCRIPTION
**Pull request by drmaas**
@RobWin PTAL

### CODE REVIEW

File: resilience4j-ratpack/src/main/java/io/github/resilience4j/ratpack/circuitbreaker/CircuitBreakerConfig.java [hunk 1]
```diff
@@ -26,7 +28,9 @@
     private Integer failureRateThreshold = DEFAULT_MAX_FAILURE_THRESHOLD;
     private Integer ringBufferSizeInClosedState = DEFAULT_RING_BUFFER_SIZE_IN_CLOSED_STATE;
     private Integer ringBufferSizeInHalfOpenState = DEFAULT_RING_BUFFER_SIZE_IN_HALF_OPEN_STATE;
-    private Predicate<Throwable> recordFailurePredicate = DEFAULT_RECORD_FAILURE_PREDICATE;
+    // default is that all exceptions are recorded, and none are ignored
+    private List<String> recordExceptions = Arrays.asList(Throwable.class.getName());
```
Comment (amityatagiri) [inline resilience4j-ratpack/src/main/java/io/github/resilience4j/ratpack/circuitbreaker/CircuitBreakerConfig.java]: +1
